 <?php
// defined('BASEPATH') OR exit('No direct script access allowed');

// class Productmodel extends CI_Model {

//     public function getproductlist()
// 	{
//         $this->load->database();
//         $query = "SELECT * FROM products";
//         return  $this->db->query($query)->result();
        
//     }public function addproduct()
// 	{
//         $this->load->database();
//         $query = "";
//         return  $this->db->query($query)->result();
        
//     }

// } <?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get product by p_id
     */
    function get_product($p_id)
    {
        return $this->db->get_where('products',array('p_id'=>$p_id))->row_array();
    }
        
    /*
     * Get all products
     */
    function get_all_products()
    {
        $this->db->order_by('p_id', 'desc');
        return $this->db->get('products')->result();
    }
        
    /*
     * function to add new product
     */
    function add_product($params)
    {
        $this->db->insert('products',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update product
     */
    function update_product($p_id,$params)
    {
        $this->db->where('p_id',$p_id);
        return $this->db->update('products',$params);
    }
    
    /*
     * function to delete product
     */
    function delete_product($p_id)
    {
        return $this->db->delete('products',array('p_id'=>$p_id));
    }
}