<?php
// defined('BASEPATH') OR exit('No direct script access allowed');

// class Product extends CI_Controller {
   
   
//    Public function ___construct(){
// 	   parent::___construct();
// 	   $this->load->database();
//    }
//     public function index()
// 	{
// 	$this->listing();
// // $row = $query;
 
// 		//$this->load->view('homecontent');
// 	}
// 	public function add(){
// 		$data['title'] = "productlist";
// 		$this->load->model('Productmodel');
// 		$data['productlist'] = $this->Productmodel->addproduct();
// 		$this->load->view('products/list', $data);

// 	}

// 	public function edit(){

// 	}
// 	public function listing(){
// 		$data['title'] = "productlist";
// 		$this->load->model('Productmodel');
// 		$data['productlist'] = $this->Productmodel->getproductlist();
// 		$this->load->view('products/list', $data);
// 	}
// 	public function delete(){

// 	}
    
// }*/


/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Product extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Product_model');
        $this->load->database();
    } 

    /*
     * Listing of products
     */
    function index(){
    $data['title'] = "product list";
        $data['productlist'] = $this->Product_model->get_all_products();
        
        $this->load->view('products/list', $data);
       // $view =  $this->load->view('product/index',$data,true);
        //$this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new product
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   $this->load->helper('url_helper');
			$this->load->helper('form_helper');
            $params = array(
				'p_name' => $this->input->post('p_name'),
				'p_description' => $this->input->post('p_description'),
				'p_price' => $this->input->post('p_price'),
				'p_img' => $this->input->post('p_img'),
				'cat_id' => $this->input->post('cat_id'),
				'subcat_id' => $this->input->post('subcat_id'),
				
            );
            
            $product_id = $this->Product_model->add_product($params);
            redirect('/code/product/index');
        }
        else
        {            
			$data['_view'] = 'products/add';
			
            $this->load->view('products/add',$data);
        }
    }  

    /*
     * Editing a product
     */
    function edit($p_id)
    {   
        // check if the product exists before trying to edit it
        $data['product'] = $this->Product_model->get_product($p_id);
        $this->load->helper('url_helper');
        if(isset($data['product']['p_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'p_name' => $this->input->post('p_name'),
					'p_description' => $this->input->post('p_description'),
					'p_price' => $this->input->post('p_price'),
					'p_img' => $this->input->post('p_img'),
					'cat_id' => $this->input->post('cat_id'),
					'subcat_id' => $this->input->post('subcat_id'),
					'created_on' => $this->input->post('created_on'),
					'updated_on' => $this->input->post('updated_on'),
                );

                $this->Product_model->update_product($p_id,$params);            
                redirect('code/product/index');
            }
            else
            {
                $this->load->view('products/edit',$data);
                //$this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The product you are trying to edit does not exist.');
    } 

    /*
     * Deleting product
     */
    function remove($p_id)
    {
        $product = $this->Product_model->get_product($p_id);
        $this->load->helper('url_helper');
        // check if the product exists before trying to delete it
        if(isset($product['p_id']))
        {
            $this->Product_model->delete_product($p_id);
            redirect('/code/product/index');
        }
        else
            show_error('The product you are trying to delete does not exist.');
    }
    
}